---
apiVersion: v1
kind: Service

metadata:
  namespace: monitoring
  name: metrics-aggregator

spec:
  selector:
    app: metrics-aggregator

  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP